-- создать таблицу "проекты"
CREATE TABLE IF NOT EXISTS projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

-- создать таблицу "задачи"
CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

-- список всех таблиц
\dt

SELECT * FROM projects;

-- Вставить тестовые данные для таблицы "projects"
INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Создать веб-приложения', 1, 'Использовать Javascript', '2020-01-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Создать приложение', 1, 'Использовать Dart', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Создать Desktop приложение', 2, 'Использовать C++', '2019-05-12');

-- Вставить тестовые данные для таблицы "tasks"
INSERT INTO tasks(name, done, projectId)
    VALUES('Загрузить Vuejs', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Создать веб-интерфейс', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Загрузить Flutter', false, 2);

INSERT INTO tasks(name, done, projectId)
    VALUES('Создать дизайн пользовательского интерфейса', false, 2);

select * from tasks;

select * from tasks where projectId = 1;